"use client";
import { motion } from "framer-motion";

export default function TermsOfService() {
  return (
    <section className="min-h-screen bg-gradient-to-r from-gray-900 via-black to-gray-900 text-white py-16 px-6">
      <motion.div
        initial={{ opacity: 0, y: -30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="max-w-4xl mx-auto"
      >
        <h1 className="text-4xl font-extrabold text-green-400 mb-6 text-center">
          Terms of Service
        </h1>
        <p className="text-gray-300 mb-6 text-center">
          By using our AI Recipe Recommendation platform, you agree to the
          following terms and conditions.
        </p>

        <div className="space-y-6 text-gray-400">
          <motion.div whileHover={{ scale: 1.02 }}>
            <h2 className="text-xl font-semibold text-green-300">
              1. Use of Service
            </h2>
            <p>
              Our service provides AI-powered recipe recommendations. You agree
              to use it responsibly and for lawful purposes only.
            </p>
          </motion.div>

          <motion.div whileHover={{ scale: 1.02 }}>
            <h2 className="text-xl font-semibold text-green-300">
              2. User Responsibilities
            </h2>
            <p>
              You are responsible for ensuring the accuracy of the information
              you provide and for safe food preparation.
            </p>
          </motion.div>

          <motion.div whileHover={{ scale: 1.02 }}>
            <h2 className="text-xl font-semibold text-green-300">
              3. Limitation of Liability
            </h2>
            <p>
              We are not liable for any health issues, damages, or losses that
              may occur as a result of using the recipes generated by our AI.
            </p>
          </motion.div>

          <motion.div whileHover={{ scale: 1.02 }}>
            <h2 className="text-xl font-semibold text-green-300">
              4. Updates to Terms
            </h2>
            <p>
              We may update these terms at any time. Continued use of our
              platform indicates your acceptance of the updated terms.
            </p>
          </motion.div>
        </div>
      </motion.div>
    </section>
  );
}
